"""
report_builder.py

Assembles the outputs of the pipeline (question, generated code, execution
result, chart, dataset schema) into a single Markdown report the user can
preview in Streamlit and download as a .md file.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any

import pandas as pd

from modules.schema_analyzer import SchemaReport


@dataclass
class Report:
    """A fully assembled analysis report."""

    title: str
    markdown: str
    generated_at: str


def _format_result_for_report(result: Any) -> str:
    """Render the execution `result` as Markdown-friendly text."""
    if isinstance(result, pd.DataFrame):
        return result.to_markdown(index=True)
    if isinstance(result, pd.Series):
        return result.to_frame(name="value").to_markdown(index=True)
    return f"```\n{result}\n```"


def build_narrative(question: str, result: Any, chart_type: str | None) -> str:
    """
    Produce a short, deterministic narrative summary describing the shape
    of the result. This is a lightweight, rule-based explanation (not
    another LLM call) so the report always renders even if the LLM/API is
    unavailable at report-build time.
    """
    lines = [f"You asked: **{question}**"]

    if isinstance(result, pd.DataFrame):
        lines.append(
            f"The analysis returned a table with **{result.shape[0]} rows** and "
            f"**{result.shape[1]} columns**."
        )
    elif isinstance(result, pd.Series):
        lines.append(f"The analysis returned **{len(result)} values**.")
    else:
        lines.append(f"The analysis returned a single value: **{result}**.")

    if chart_type:
        lines.append(f"A **{chart_type} chart** was generated to help visualize this result.")
    else:
        lines.append("No chart was generated automatically for this type of result.")

    return " ".join(lines)


def build_report(
    question: str,
    generated_code: str,
    result: Any,
    schema: SchemaReport,
    chart_type: str | None = None,
    dataset_name: str = "uploaded_dataset.csv",
) -> Report:
    """
    Build a full Markdown report for one analysis run.

    Args:
        question: The user's original natural language question.
        generated_code: The pandas code that was executed.
        result: The `result` value produced by execution.
        schema: The dataset's SchemaReport.
        chart_type: Human-readable chart type if one was generated.
        dataset_name: Display name of the source file.

    Returns:
        A Report with rendered Markdown ready for display/download.
    """
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    narrative = build_narrative(question, result, chart_type)

    md = f"""# Automated Data Analysis Report

**Generated:** {timestamp}
**Dataset:** {dataset_name}

## Dataset Summary
- Rows: {schema.row_count}
- Columns: {schema.column_count}
- Numerical columns: {', '.join(schema.numerical_columns) or 'none'}
- Categorical columns: {', '.join(schema.categorical_columns) or 'none'}
- Missing cells: {schema.total_missing_cells}

## Question
{question}

## Generated Code
```python
{generated_code}
```

## Result
{_format_result_for_report(result)}

## Narrative Explanation
{narrative}

---
*Report generated by the Automated Data Analysis Agent.*
"""

    return Report(title="Automated Data Analysis Report", markdown=md, generated_at=timestamp)
